name: Build LaTeX Thesis document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
      - name: Upload pdf file    
        uses: actions/upload-artifact@v2
        with:
         name: Thesis
         path: Thesis.pdf
      - name: Workaround for container permissions
        run: |
          sudo chown -R $USER:$(id -gn $USER) /home
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
            name: Thesis
